### Transforming code into idioatic python
- Replace traditional index manupulation with python core looping idiomatic

In [1]:
# looping over a range of numbers
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [3]:
# idiomatic programming
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

### looping over a collection

In [8]:
colors = ['blue','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

blue green yellow purple 

In [9]:
for color in colors:
    print(color,end=" ")

blue green yellow purple 

### looping backwards

In [10]:
colors = ['blue','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green blue 

In [12]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green blue 

### looping in sorted list


In [13]:
colors = ['blue','green','yellow','purple']
for color in sorted(colors):
    print(color,end=" ")

blue green purple yellow 

In [14]:
colors = ['blue','green','yellow','purple']
for color in sorted(colors,reverse= True):
    print(color,end=" ")

yellow purple green blue 

###
- if x<=y and y<=z:
- ifx<=y<=z:

### Pandas

In [15]:
import pandas as pd

In [19]:
dt ={'Id':[11,12,13,14,15],
    'first_name':['A','B','C','D','E'],
    'company':['aa','bb','cc','dd','ee'],
    'adders':['hyd','hyd','hyd','hyd','hyd']}
mydt = pd.DataFrame(dt)

In [20]:
print(mydt)

   Id first_name company adders
0  11          A      aa    hyd
1  12          B      bb    hyd
2  13          C      cc    hyd
3  14          D      dd    hyd
4  15          E      ee    hyd


In [21]:
import os

In [23]:
os.chdir("D:\\myData\\")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\myData\\'

In [28]:
mydt.to_csv('workingFile.csv',index=False)

### reading the data from CSV file

In [26]:
mydata =pd.read_csv('workingFile.csv')

In [27]:
print(mydata)

   Id first_name company adders
0  11          A      aa    hyd
1  12          B      bb    hyd
2  13          C      cc    hyd
3  14          D      dd    hyd
4  15          E      ee    hyd


In [29]:
   cd desktop                     

[WinError 2] The system cannot find the file specified: 'desktop'
C:\Users\sys60\Desktop


In [32]:
mydata1 = pd.read_csv('WorkingFile.csv',skiprows=[1,2,3],
                     names=["custId","name","company","address"])

In [33]:
print(mydata1)

  custId        name  company address
0     Id  first_name  company  adders
1     14           D       dd     hyd
2     15           E       ee     hyd


### Numpy package
- Numpy array are bit like python lis
- Numpy is also one of data structure
- Numpy short name for " Numeric python" or"numerical python"

In [34]:
import numpy as np

In [35]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [37]:
array =np.array(li)
print(array)

[1 2 3 4 5]


In [38]:
a1 = np.array([(1,2,3,),(4,5,6)])
print(a1.shape)
a2= np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [39]:
a1 =np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
a1 = np.array([(1,2,3)])
a2 =np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [41]:
a1 = np.array([(1,2,3)])
a2 =np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [1]:
# Python program to draw  
# Spiral Square   
# using Turtle Programming 
import turtle   
wn = turtle.Screen()  
wn.title("Turtle") 
skk = turtle.Turtle() 
skk.color("red") 
 
def sqrfunc(size): 
   for i in range(4): 
       skk.fd(size) 
       skk.left(90) 
       size = size-5
 
sqrfunc(146) 
sqrfunc(126) 
sqrfunc(106) 
sqrfunc(86) 
sqrfunc(66) 
sqrfunc(46) 
sqrfunc(26) 